# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
l_2F1 <- function(q_pri, p_pri, alpha, alpha_til, s, x, lmlt) {
    .Call(`_DSDprior_l_2F1`, q_pri, p_pri, alpha, alpha_til, s, x, lmlt)
}

#'@export
l_pri_s2 <- function(s, pri_s2) {
    .Call(`_DSDprior_l_pri_s2`, s, pri_s2)
}

#'@export
sample_blmm <- function(y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning) {
    .Call(`_DSDprior_sample_blmm`, y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning)
}

sample_logitm <- function(y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning) {
    .Call(`_DSDprior_sample_logitm`, y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning)
}

#'
sample_bprobm <- function(y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning) {
    .Call(`_DSDprior_sample_bprobm`, y, X, Z_list, K_list, rank_K_g, A_list, e_list, S_beta, pri_s2e, pri_s2b, pri_s2g, beta_init, g_init_list, S2g_init, s2e_init, FFe, FFb, FFg, niter, pr, thin, ntuning, stop_tuning)
}

